name: GitHub Actions CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop
      - githubactions*
      - feature/**
      - fix/**
      - pr/**

env:
    B2_CI_VERSION: 1
    B2_VARIANT: release
    B2_FLAGS: warnings=extra warnings-as-errors=on

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "COMMENT=docs Job 0"
            buildtype: "docs"
            packages: "docbook docbook-xml docbook-xsl xsltproc libsaxonhe-java default-jre-headless flex bison rsync"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "docs"
          - name: "COMMENT=codecov.io LCOV_BRANCH_COVERAGE=0 B2_ Job 1"
            buildtype: "codecov"
            packages: "g++-8"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-8"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "codecov.io"
            lcov_branch_coverage: "0"
            b2_cxxstd: "11"
            b2_toolset: "gcc-8"
            b2_defines: "BOOST_NO_STRESS_TEST=1"
          - name: "COMMENT=valgrind B2_TOOLSET=clang-6.0 B2_CXXS Job 2"
            buildtype: "valgrind"
            packages: "clang-6.0 libc6-dbg libstdc++-8-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-6.0"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "6.0"
            comment: "valgrind"
            b2_toolset: "clang-6.0"
            b2_cxxstd: "11,14"
            b2_defines: "BOOST_NO_STRESS_TEST=1"
            b2_variant: "debug"
            b2_testflags: "testing.launcher=valgrind"
            valgrind_opts: "--error-exitcode=1"
          - name: "COMMENT=asan B2_VARIANT=debug B2_TOOLSET=clan Job 3"
            buildtype: "boost"
            packages: "clang-11 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-11"
            sources: ""
            llvm_os: "bionic"
            llvm_ver: "11"
            comment: "asan"
            b2_variant: "debug"
            b2_toolset: "clang-11"
            b2_cxxstd: "17"
            b2_asan: "1"
            b2_defines: "BOOST_NO_STRESS_TEST=1"
          - name: "COMMENT=ubsan B2_VARIANT=debug B2_TOOLSET=cla Job 4"
            buildtype: "boost"
            packages: "clang-11 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-11"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "11"
            comment: "ubsan"
            b2_variant: "debug"
            b2_toolset: "clang-11"
            b2_cxxstd: "17"
            b2_ubsan: "1"
            b2_defines: "BOOST_NO_STRESS_TEST=1"
          - name: "B2_TOOLSET=gcc-4.8 B2_CXXSTD=11 Job 9"
            buildtype: "boost"
            packages: "g++-4.8"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:14.04"
            cxx: "g++-4.8"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-4.8"
            b2_cxxstd: "11"
          - name: "B2_TOOLSET=gcc-4.9 B2_CXXSTD=11 Job 10"
            buildtype: "boost"
            packages: "g++-4.9"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-4.9"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-4.9"
            b2_cxxstd: "11"
          - name: "B2_TOOLSET=gcc-5 B2_CXXSTD=11 Job 11"
            buildtype: "boost"
            packages: "g++-5"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-5"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-5"
            b2_cxxstd: "11"
          - name: "B2_TOOLSET=gcc-6 B2_CXXSTD=11,14 Job 12"
            buildtype: "boost"
            packages: "g++-6"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-6"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-6"
            b2_cxxstd: "11,14"
          - name: "B2_TOOLSET=gcc-7 B2_CXXSTD=14,17 Job 13"
            buildtype: "boost"
            packages: "g++-7"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-7"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-7"
            b2_cxxstd: "14,17"
          - name: "B2_TOOLSET=gcc-8 B2_CXXSTD=17,2a Job 14"
            buildtype: "boost"
            packages: "g++-8"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-8"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-8"
            b2_cxxstd: "17,2a"
          - name: "B2_TOOLSET=gcc-9 B2_CXXSTD=17,2a Job 15"
            buildtype: "boost"
            packages: "g++-9"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-9"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-9"
            b2_cxxstd: "17,2a"
          - name: "COMMENT=standalone CXX=g++-9 Job 16"
            buildtype: "standalone"
            packages: "g++-9"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++-9"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "standalone"
          - name: "B2_TOOLSET=gcc-10 B2_CXXSTD=17,2a Job 17"
            buildtype: "boost"
            packages: "g++-10"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            cxx: "g++-10"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "gcc-10"
            b2_cxxstd: "17,2a"
          - name: "COMMENT=standalone CXX=g++-10 Job 18"
            buildtype: "standalone"
            packages: "g++-10"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            cxx: "g++-10"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "standalone"
          - name: "B2_TOOLSET=clang-3.8 B2_CXXSTD=11 Job 19"
            buildtype: "boost"
            packages: "clang-3.8"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:14.04"
            cxx: "clang++-3.8"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "clang-3.8"
            b2_cxxstd: "11"
          - name: "B2_TOOLSET=clang-4.0 B2_CXXSTD=11,14 Job 20"
            buildtype: "boost"
            packages: "clang-4.0 libstdc++-6-dev"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-4.0"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "4.0"
            b2_toolset: "clang-4.0"
            b2_cxxstd: "11,14"
          - name: "B2_TOOLSET=clang-5.0 B2_CXXSTD=11,14 Job 21"
            buildtype: "boost"
            packages: "clang-5.0 libstdc++-7-dev"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-5.0"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "5.0"
            b2_toolset: "clang-5.0"
            b2_cxxstd: "11,14"
          - name: "B2_TOOLSET=clang-6.0 B2_CXXSTD=14,17 Job 22"
            buildtype: "boost"
            packages: "clang-6.0 libc6-dbg libstdc++-8-dev"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-6.0"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "6.0"
            b2_toolset: "clang-6.0"
            b2_cxxstd: "14,17"
          - name: "B2_TOOLSET=clang-7 B2_CXXSTD=17 Job 23"
            buildtype: "boost"
            packages: "clang-7"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-7"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "7"
            b2_toolset: "clang-7"
            b2_cxxstd: "17"
          - name: "B2_TOOLSET=clang-8 B2_CXXSTD=17 Job 24"
            buildtype: "boost"
            packages: "clang-8"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-8"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "8"
            b2_toolset: "clang-8"
            b2_cxxstd: "17"
          - name: "B2_TOOLSET=clang-9 B2_CXXSTD=17,2a Job 25"
            buildtype: "boost"
            packages: "clang-9 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-9"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "9"
            b2_toolset: "clang-9"
            b2_cxxstd: "17,2a"
          - name: "COMMENT=standalone CXX=clang++-9 Job 26"
            buildtype: "standalone"
            packages: "clang-9 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "clang++-9"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "9"
            comment: "standalone"
          - name: "B2_TOOLSET=clang-10 B2_CXXSTD=17,2a Job 27"
            buildtype: "boost"
            packages: "clang-10 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-10"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "10"
            b2_toolset: "clang-10"
            b2_cxxstd: "17,2a"
          - name: "COMMENT=standalone CXX=clang++-10 Job 28"
            buildtype: "standalone"
            packages: "clang-10 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-10"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "10"
            comment: "standalone"
          - name: "B2_TOOLSET=clang-11 B2_CXXSTD=17,2a Job 29"
            buildtype: "boost"
            packages: "clang-11 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-11"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "11"
            b2_toolset: "clang-11"
            b2_cxxstd: "17,2a"
          - name: "COMMENT=standalone CXX=clang++-11 Job 30"
            buildtype: "standalone"
            packages: "clang-11 libstdc++-9-dev"
            packages_to_remove: ""
            os: "ubuntu-18.04"
            cxx: "clang++-11"
            sources: ""
            llvm_os: "xenial"
            llvm_ver: "11"
            comment: "standalone"
          - name: "COMMENT=Coverity Scan B2_TOOLSET=clang Job 31"
            buildtype: "coverity"
            packages: "clang"
            packages_to_remove: ""
            os: "ubuntu-20.04"
            container: "ubuntu:16.04"
            cxx: "g++"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "Coverity Scan"
            b2_toolset: "clang"
          - name: "msvc-14.1"
            buildtype: "boost"
            packages: ""
            os: "windows-2016"
            cxx: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "msvc-14.1"
            b2_cxxstd: "11,14,17"
          - name: "msvc-14.1 standalone"
            buildtype: "standalone-windows"
            packages: ""
            os: "windows-2016"
            cxx: "msvc-14.1"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "standalone"
          - name: "msvc-14.2"
            buildtype: "boost"
            packages: ""
            os: "windows-2019"
            cxx: ""
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            b2_toolset: "msvc-14.2"
            b2_cxxstd: "17,latest"
          - name: "msvc-14.2 standalone"
            buildtype: "standalone-windows"
            packages: ""
            os: "windows-2019"
            cxx: "msvc-14.2"
            sources: ""
            llvm_os: ""
            llvm_ver: ""
            comment: "standalone"

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup-container
        with:
          container: ${{ matrix.container }}

      - uses: ./.github/actions/setup-packages
        with:
          install: ${{ matrix.packages }}
          remove: ${{ matrix.packages_to_remove }}
          sources: ${{ matrix.sources }}
          os: ${{ matrix.llvm_os }}
          llvm_version: ${{ matrix.llvm_ver }}

      - name: linux
        if: runner.os == 'Linux'
        shell: bash
        env:
          CXX: ${{ matrix.cxx }}
          COMMENT: ${{ matrix.comment }}
          LCOV_BRANCH_COVERAGE: ${{ matrix.lcov_branch_coverage }}
          B2_CXXSTD: ${{ matrix.b2_cxxstd }}
          B2_TOOLSET: ${{ matrix.b2_toolset }}
          B2_DEFINES: ${{ matrix.b2_defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          B2_TESTFLAGS: ${{ matrix.b2_testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
          B2_ASAN: ${{ matrix.b2_asan }}
          B2_UBSAN: ${{ matrix.b2_ubsan }}
          TRAVIS_BRANCH: ${{ github.base_ref }}
          DRONE_BUILD_EVENT: ${{ github.event_name }}
          DRONE_COMMIT: ${{ github.sha }}
          DRONE_JOB_BUILDTYPE: ${{ matrix.buildtype }}
          TRAVIS_OS_NAME: "linux"
        run: |
          export DRONE_BRANCH=${TRAVIS_BRANCH:-$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')}
          export DRONE_REPO=$(basename $GITHUB_REPOSITORY)
          . .drone/drone.sh

      - name: windows
        if: runner.os == 'Windows'
        shell: cmd
        env:
          CXX: ${{ matrix.cxx }}
          SOURCES: ${{ matrix.sources }}
          LLVM_OS: ${{ matrix.llvm_os }}
          LLVM_VER: ${{ matrix.llvm_ver }}
          PACKAGES: ${{ matrix.packages }}
          COMMENT: ${{ matrix.comment }}
          LCOV_BRANCH_COVERAGE: ${{ matrix.lcov_branch_coverage }}
          B2_CXXSTD: ${{ matrix.b2_cxxstd }}
          B2_TOOLSET: ${{ matrix.b2_toolset }}
          B2_DEFINES: ${{ matrix.b2_defines }}
          B2_VARIANT: ${{ matrix.b2_variant }}
          B2_TESTFLAGS: ${{ matrix.b2_testflags }}
          VALGRIND_OPTS: ${{ matrix.valgrind_opts }}
          B2_ASAN: ${{ matrix.b2_asan }}
          B2_UBSAN: ${{ matrix.b2_ubsan }}
          GHA_TARGET_BRANCH: ${{ github.base_ref }}
          TRAVIS_BRANCH: ${{ github.base_ref }}
          DRONE_JOB_BUILDTYPE: ${{ matrix.buildtype }}
          DRONE_COMMIT_BRANCH: ${{ github.base_ref }}
          DRONE_REPO: ${{ github.repository }}
          TRAVIS_OS_NAME: "windows"
        run: |
          call .drone\drone.bat
